"""empty message

Revision ID: 81a3d868d049
Revises: 1ca760c2c9f8
Create Date: 2025-04-20 23:41:10.316317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81a3d868d049'
down_revision: Union[str, None] = '1ca760c2c9f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'users', 'medias', ['avatar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'avatar_id')
    # ### end Alembic commands ###
